### ISSUE TITLE
New recipe: Run a test and check a budget using testspecs

### ISSUE THREAD

**Issue by tkadlec** [WebPageTest/WebPageTest-API-Recipes#31]
While all the docs here: https://github.com/WebPageTest/webpagetest-api/wiki/Test-Specs are about the CLI, we should also be able to run testspecs programmatically as well. Let's get a recipe setup for checking a budget (maybe something like FCP or LCP) and outputting the results.

**Comment by Siddhantshukla814** [comment]
https://github.com/WebPageTest/WebPageTest-API-Recipes/pull/34
